#!/usr/bin/env bash
#MISE description="Install/update tmux plugins"
if [ -d "$HOME"/.tmux/plugins/tpm ]; then
  git -C "$HOME"/.tmux/plugins/tpm pull
else
  git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
fi
"$HOME"/.tmux/plugins/tpm/scripts/install_plugins.sh
