[tools]
go = "1.26.1"
rust = "1.94.0"
uv = "0.10.9"
lua = "5.5.0"
java = "lts"
maven = "3.9.13"
node = "25.8.0"
lazydocker = "0.24.4"
lazygit = "0.59.0"
fzf = "0.70.0"
duf = "0.9.1"
dive = "0.13.1"
yq = "4.52.4"
jq = "1.8.1"
direnv = "2.37.1"
sops = "3.12.1"
bat = "0.26.1"
eza = "0.23.4"
fd = "10.4.1"
delta = "0.18.2"
rg = "15.1.0"
difftastic = "0.67.0"
choose = "1.3.7"
just = "1.46.0"
zoxide = "0.9.9"
starship = "1.24.2"
terraform = "1.14.6"
pandoc = "3.9"
gh = "2.87.3"
tmux = "3.6a"
kubectl = "1.35.2"
k9s = "0.50.18"
lnav = "0.13.2"
neovim = "0.11.6"
docker-cli = "29.3.0"
docker-compose = "5.0.2"
pipx = "1.8.0"
"pipx:harlequin[postgres,mysql,s3]" = "2.5.1"
"pipx:httpie" = "3.2.4"
"pipx:jrnl" = "4.3"
"pipx:visidata" = "3.3"
"pipx:mitmproxy" = "12.2.1"
"pipx:ansible" = "13.4.0"
"pipx:ansible-core" = "2.20.3"
"pipx:stringshift[full]" = "0.1.2"
"github:veeso/termscp" = "0.19.1"
"github:dalance/procs" = "0.14.11"

[tasks.claude-install]
description = "Install/update Claude Code native binary"
run = "curl -fsSL https://claude.ai/install.sh | bash"

[tasks.tmux-plugins-install]
description = "Install/update tmux plugins"
run = """
  if [ -d "$HOME"/.tmux/plugins/tpm ]; then
    git -C "$HOME"/.tmux/plugins/tpm pull
  else
    git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
  fi
  "$HOME"/.tmux/plugins/tpm/scripts/install_plugins.sh
"""
