# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
scan_timeout = 10                                    # Wait 10 milliseconds for starship to check files under the current directory.
add_newline = false

format = """
$directory${custom.git_dirty}$git_branch$git_commit $git_metrics $git_status
$character
"""

right_format = """
$direnv $status
"""

[git_metrics]
disabled = false
only_nonzero_diffs = true
# format = '[\($added/$deleted\)]($added_style)'
format = '([+$added ]($added_style))([-$deleted]($deleted_style))'
added_style = 'fg:#464ad6 bold italic'
deleted_style = 'fg:#d64646 bold italic'

[directory]
use_os_path_sep = false
truncation_length = 0
truncate_to_repo = false
style = "bold cyan"

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_replace_symbol = '➜ (bold red)'

[git_branch]
format = '[$branch]($style)'
style = 'fg:#6c6c6c bold italic'
ignore_branches = ["HEAD"]

[git_commit]
format = '[detached at @$hash]($style)'
style = 'fg:#6c6c6c bold italic'
only_detached = true
commit_hash_length = 7

[custom.git_dirty]
command = "bash -c 'git status --porcelain | grep -q . && echo \"*\"'"
when = "git rev-parse --is-inside-work-tree"
format = "[$output]($style)"
style = 'fg:#6c6c6c bold italic'

[git_status]
# Only show ahead/behind arrows
ahead = "[⇡](cyan)"
behind = "[⇣](red)"
diverged = "⇕"
conflicted = ""
deleted = ""
renamed = ""
modified = ""
staged = ""
untracked = ""
stashed = ""
format = '$ahead_behind'

[direnv]
disabled = false

[fill]
symbol = "─"
style = "bold grey"
